namespace Oxide.Plugins
{
    [Info("HeliInbound", "Wulf/lukespragg", "0.1.1", ResourceId = 1457)]
    [Description("Notifies players when a helicopter is inbound.")]

    class HeliInbound : RustPlugin
    {
        // Do NOT edit this file, instead edit HeliInbound.json in server/<identity>/oxide/config

        string Notification => Config.Get<string>("Notification");

        protected override void LoadDefaultConfig() => Config["Notification"] = "Helicopter inbound!";

        void OnEntitySpawned(BaseEntity entity)
        {
            if (entity.LookupShortPrefabName().Equals("patrolhelicopter.prefab"))  PrintToChat(Notification);
        }
    }
}
