ï»¿using System;

namespace Oxide.Plugins
{
    [Info("Announcer", "Wulf/lukespragg", 0.1, ResourceId = 1465)]
    [Description("Broadcasts customizable messages when players join/quit.")]

    class Announcer : TheForestPlugin
    {
        // Do NOT edit this file, instead edit Announcer.json in server/<identity>/oxide/config

        #region Configuration

        string PlayerJoined => GetConfig("PlayerJoined", "{name} joined the survivors");
        string PlayerQuit => GetConfig("PlayerQuit", "{name} abandoned the survivors");

        protected override void LoadDefaultConfig()
        {
            Config["PlayerJoined"] = PlayerJoined;
            Config["PlayerQuit"] = PlayerQuit;
            SaveConfig();
        }

        #endregion

        #region Broadcast Messages

        void OnPlayerConnected(BoltConnection connection)
        {
            if (connection == null) return;

            var steamId = forest.IdFromConnection(connection);
            var name = forest.NameFromId(steamId);
            if (CoopLobby.Instance.MemberCount > 1) forest.BroadcastChat(PlayerJoined.Replace("{name}", name));
        }

        void OnPlayerDisconnected(BoltConnection connection)
        {
            if (connection == null) return;

            var steamId = forest.IdFromConnection(connection);
            var name = forest.NameFromId(steamId);
            if (CoopLobby.Instance.MemberCount > 1) forest.BroadcastChat(PlayerQuit.Replace("{name}", name));
        }

        #endregion

        #region Helper Methods

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        #endregion
    }
}
