using System;
using System.Collections.Generic;
using System.Reflection;
using Rust;
using UnityEngine;
using Oxide.Core;

namespace Oxide.Plugins
{
    [Info("Godmode", "Wulf/lukespragg", "3.0.8", ResourceId = 673)]
    [Description("Allows players with permission to become invincible/invulnerable")]

    class Godmode : RustPlugin
    {
        // Do NOT edit this file, instead edit Godmode.json in oxide/config and Godmode.en.json in the oxide/lang directory,
        // or create a new language file for another language using the 'en' file as a default.

        #region Configuration

        const string permGod = "godmode.allowed";

        bool canBeHurt;
        bool canBeLooted;
        bool canHurtPlayers;
        bool canLootPlayers;
        bool infiniteRun;
        bool informOnAttack;
        bool prefixEnabled;
        string prefixFormat;

        protected override void LoadDefaultConfig()
        {
            Config["CanBeHurt"] = canBeHurt = GetConfig("CanBeHurt", false);
            Config["CanBeLooted"] = canBeLooted = GetConfig("CanBeLooted", false);
            Config["CanHurtPlayers"] = canHurtPlayers = GetConfig("CanHurtPlayers", true);
            Config["CanLootPlayers"] = canLootPlayers = GetConfig("CanLootPlayers", true);
            Config["InfiniteRun"] = infiniteRun = GetConfig("InfiniteRun", true);
            Config["InformOnAttack"] = informOnAttack = GetConfig("InformOnAttack", true);
            Config["PrefixEnabled"] = prefixEnabled = GetConfig("PrefixEnabled", true);
            Config["PrefixFormat"] = prefixFormat = GetConfig("PrefixFormat", "[God]");
            SaveConfig();
        }

        #endregion

        #region Localization

        void LoadDefaultMessages()
        {
            lang.RegisterMessages(new Dictionary<string, string>            {
                {"Disabled", "You have disabled godmode"},
                {"DisabledBy", "Your godmode has been disabled by {0}"},
                {"DisabledFor", "You have disabled godmode for {0}"},
                {"Enabled", "You have enabled godmode"},
                {"EnabledBy", "Your godmode has been enabled by {0}"},
                {"EnabledFor", "You have enabled godmode for {0}"},
                {"Godlist", "Players with godmode enabled:"},
                {"GodlistNone", "No players have godmode enabled"},
                {"InformAttacker", "{0} is in godmode and can't take any damage"},
                {"InformVictim", "{0} just tried to deal damage to you"},
                {"NoLooting", "You are not allowed to loot a player with godmode"},
                {"NotAllowed", "You are not allowed to use this command"},
                {"PlayerNotFound", "No players were found with that name"}
            }, this);
        }

        #endregion

        #region Initialization

        void Loaded()
        {
            #if !RUST
            throw new NotSupportedException("This plugin does not support this game");
            #endif

            LoadDefaultConfig();
            LoadDefaultMessages();
            LoadSavedData();
            Unsubscribe(nameof(OnRunPlayerMetabolism));
            permission.RegisterPermission(permGod, this);
        }

        void LoadSavedData()
        {
            storedData = Interface.Oxide.DataFileSystem.ReadObject<StoredData>(Title);
            foreach (var god in storedData.Gods) gods[god.GetUserId()] = god;
        }

        void SaveData() => Interface.Oxide.DataFileSystem.WriteObject(Title, storedData);

        #endregion

        class StoredData
        {
            public readonly HashSet<PlayerInfo> Gods = new HashSet<PlayerInfo>();
        }

        class PlayerInfo
        {
            public string UserId;
            public string Name;

            public PlayerInfo()
            {
            }

            public PlayerInfo(BasePlayer player)
            {
                UserId = player.userID.ToString();
                Name = player.displayName;
            }

            public ulong GetUserId()
            {
                ulong userId;
                return !ulong.TryParse(UserId, out userId) ? 0 : userId;
            }
        }

        StoredData storedData;
        readonly Hash<ulong, PlayerInfo> gods = new Hash<ulong, PlayerInfo>();
        readonly Dictionary<BasePlayer, long> playerInformHistory = new Dictionary<BasePlayer, long>();
        readonly DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0);
        readonly FieldInfo displayName = typeof(BasePlayer).GetField("_displayName", (BindingFlags.NonPublic | BindingFlags.Instance));

        void Unload() => SaveData();
        void OnServerSave() => SaveData();

        void OnPlayerInit(BasePlayer player)
        {
            if (player.HasPlayerFlag(BasePlayer.PlayerFlags.ReceivingSnapshot))
            {
                timer.Once(2, () => OnPlayerInit(player));
                return;
            }
            if (gods[player.userID] == null) return;
            ModifyMetabolism(player, true);
            if (prefixEnabled && !player.displayName.Contains(prefixFormat))
                displayName.SetValue(player, $"{prefixFormat} {player.displayName}");
            else
                displayName.SetValue(player, player.displayName.Replace(prefixFormat, "").Trim());
        }

        [ChatCommand("god")]
        void God(BasePlayer player, string command, string[] args)
        {
            if (!IsAllowed(player, permGod)) return;

            if (args.Length == 0)
            {
                if (gods[player.userID] != null)
                {
                    DisableGodmode(player);
                    Unsubscribe(nameof(OnRunPlayerMetabolism));
                    Reply(player, Lang("Disabled", player.UserIDString));
                }
                else
                {
                    EnableGodmode(player);
                    Subscribe(nameof(OnRunPlayerMetabolism));
                    Reply(player, Lang("Enabled", player.UserIDString));
                }

                return;
            }

            var target = rust.FindPlayer(args[0]);
            if (!target)
                Reply(player, Lang("PlayerNotFound", player.UserIDString));
            else
                ToggleGodmode(player, target);
        }

        [ChatCommand("gods")]
        void Godlist(BasePlayer player)
        {
            if (!IsAllowed(player, permGod)) return;

            Reply(player, Lang("GodList", player.UserIDString));
            if (gods.Count == 0)
                Reply(player, Lang("GodListNone", player.UserIDString));
            else
                foreach (var god in gods) Reply(player, $"{god.Value.Name} [{god.Value.UserId}]");
        }

        object CanBeWounded(BasePlayer player) => !canBeHurt && gods[player.userID] != null ? (object)false : null;

        void OnEntityTakeDamage(BaseEntity entity, HitInfo info)
        {
            var player = entity as BasePlayer;
            var attacker = info.Initiator as BasePlayer;

            if (!player) return;
            if (!canBeHurt && gods[player.userID] != null)
            {
                NullifyDamage(ref info);
                if (informOnAttack) InformPlayers(player, attacker);
            }

            if (!attacker) return;
            if (!canHurtPlayers && gods[attacker.userID] != null) NullifyDamage(ref info);
        }

        object CanLootPlayer(BasePlayer target, BasePlayer looter)
        {
            if ((!canBeLooted && gods[target.userID] != null) || (!canLootPlayers && gods[looter.userID] != null))
            {
                NextTick(() =>
                {
                    looter.EndLooting();
                    Reply(looter, Lang("NoLooting", looter.UserIDString));
                });
                return false;
            }

            return null;
        }

        void OnLootPlayer(BasePlayer looter, BasePlayer target)
        {
            if (!target) return;
            if (gods[target.userID] != null)
            {
                NextTick(() =>
                {
                    looter.EndLooting();
                    Reply(looter, Lang("NoLooting", looter.UserIDString));
                });
            }
        }

        void DisableGodmode(BasePlayer player)
        {
            storedData.Gods.RemoveWhere(info => info.GetUserId() == player.userID);
            gods.Remove(player.userID);
            ModifyMetabolism(player, false);
            displayName.SetValue(player, player.displayName.Replace(prefixFormat, "").Trim());
        }

        void EnableGodmode(BasePlayer player)
        {
            var info = new PlayerInfo(player);
            storedData.Gods.Add(info);
            gods[player.userID] = info;
            ModifyMetabolism(player, true);
            if (prefixEnabled && !player.displayName.Contains(prefixFormat))
                displayName.SetValue(player, $"{prefixFormat} {player.displayName}");
            else
                displayName.SetValue(player, player.displayName.Replace(prefixFormat, "").Trim());
        }

        static void ModifyMetabolism(BasePlayer player, bool isGod)
        {
            if (isGod)
            {
                player.health = 100;
                player.metabolism.bleeding.max = 0;
                player.metabolism.bleeding.value = 0;
                player.metabolism.calories.min = 500;
                player.metabolism.calories.value = 500;
                player.metabolism.dirtyness.max = 0;
                player.metabolism.dirtyness.value = 0;
                player.metabolism.heartrate.min = 0.5f;
                player.metabolism.heartrate.max = 0.5f;
                player.metabolism.heartrate.value = 0.5f;
                player.metabolism.hydration.min = 500;
                player.metabolism.hydration.value = 500;
                player.metabolism.oxygen.min = 1;
                player.metabolism.oxygen.value = 1;
                player.metabolism.poison.max = 0;
                player.metabolism.poison.value = 0;
                player.metabolism.radiation_level.max = 0;
                player.metabolism.radiation_level.value = 0;
                player.metabolism.radiation_poison.max = 0;
                player.metabolism.radiation_poison.value = 0;
                player.metabolism.temperature.min = 32;
                player.metabolism.temperature.max = 32;
                player.metabolism.temperature.value = 32;
                player.metabolism.wetness.max = 0;
                player.metabolism.wetness.value = 0;
            }
            else
            {
                player.metabolism.bleeding.min = 0;
                player.metabolism.bleeding.max = 1;
                player.metabolism.calories.min = 0;
                player.metabolism.calories.max = 500;
                player.metabolism.comfort.min = 0;
                player.metabolism.comfort.max = 1;
                player.metabolism.dirtyness.min = 0;
                player.metabolism.dirtyness.max = 100;
                player.metabolism.heartrate.min = 0;
                player.metabolism.heartrate.max = 1;
                player.metabolism.hydration.min = 0;
                player.metabolism.hydration.max = 500;
                player.metabolism.oxygen.min = 0;
                player.metabolism.oxygen.max = 1;
                player.metabolism.poison.min = 0;
                player.metabolism.poison.max = 100;
                player.metabolism.radiation_level.min = 0;
                player.metabolism.radiation_level.max = 100;
                player.metabolism.radiation_poison.min = 0;
                player.metabolism.radiation_poison.max = 500;
                player.metabolism.temperature.min = -100;
                player.metabolism.temperature.max = 100;
                player.metabolism.wetness.min = 0;
                player.metabolism.wetness.max = 1;
            }
            player.metabolism.SendChangesToClient();
        }

        object OnRunPlayerMetabolism(PlayerMetabolism metabolism, BaseCombatEntity entity)
        {
            if (!(entity is BasePlayer)) return null;

            var player = entity.ToPlayer();
            player.SetPlayerFlag(BasePlayer.PlayerFlags.NoSprint, false);
            if (infiniteRun && gods[player.userID] != null) return true;

            return null;
        }

        void InformPlayers(BasePlayer victim, BasePlayer attacker)
        {
            if (!victim || !attacker) return;
            if (victim == attacker) return;

            if (!playerInformHistory.ContainsKey(attacker)) playerInformHistory.Add(attacker, 0);
            if (!playerInformHistory.ContainsKey(victim)) playerInformHistory.Add(victim, 0);

            if (GetTimestamp() - playerInformHistory[attacker] > 15)
            {
                Reply(victim, Lang("InformVictim", victim.UserIDString), attacker.displayName);
                playerInformHistory[victim] = GetTimestamp();
            }

            if (GetTimestamp() - playerInformHistory[victim] > 15)
            {
                Reply(attacker, Lang("InformAttacker", attacker.UserIDString), victim.displayName);
                playerInformHistory[victim] = GetTimestamp();
            }
        }

        static void NullifyDamage(ref HitInfo info)
        {
            info.damageTypes = new DamageTypeList();
            info.HitMaterial = 0;
            info.PointStart = Vector3.zero;
        }

        void ToggleGodmode(BasePlayer player, BasePlayer target)
        {
            if (gods[target.userID] != null)
            {
                DisableGodmode(target);
                Reply(player, Lang("YouDisabled", player.UserIDString), target.displayName);
                Reply(target, Lang("DisabledBy", player.UserIDString), player.displayName);
            }
            else
            {
                EnableGodmode(target);
                Reply(player, Lang("YouEnabled", player.UserIDString), target.displayName);
                Reply(target, Lang("EnabledBy", player.UserIDString), player.displayName);
            }
        }

        #region Helper Methods

        void Log(string msg) => Puts($"{msg}");

        void Warning(string msg) => PrintWarning($"{msg}");

        long GetTimestamp() => Convert.ToInt64((DateTime.UtcNow.Subtract(epoch)).TotalSeconds);

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        string Lang(string key, string userId = null) => lang.GetMessage(key, this, userId);

        bool IsAllowed(BasePlayer player, string perm)
        {
            if (permission.UserHasPermission(player.UserIDString, perm)) return true;
            Reply(player, Lang("NotAllowed", player.UserIDString));
            return false;
        }

        bool IsAdmin(string userId) => permission.UserHasGroup(userId, "admin");

        void Reply(BasePlayer player, string message, string args = null) => PrintToChat(player, $"{message}", args);

        #endregion
    }
}
