/*
TODO:
- Add no permission message for chat command
- Allow localization of item names
*/

using System;
using System.Collections.Generic;
using Oxide.Core;
using Oxide.Core.Configuration;

namespace Oxide.Plugins
{
    [Info("MasterKey", "Wulf/lukespragg", "0.4.7", ResourceId = 1151)]
    [Description("Gain access to any locked object with permissions.")]

    class MasterKey : RustPlugin
    {
        // Do NOT edit this file, instead edit MasterKey.json in oxide/config and MasterKey.en.json in oxide/lang,
        // or create a language file for another language using the 'en' file as a default.

        #region Initialization

        readonly DynamicConfigFile dataFile = Interface.Oxide.DataFileSystem.GetFile("MasterKey");
        Dictionary<ulong, bool> playerPrefs = new Dictionary<ulong, bool>();

        void Init()
        {
            LoadDefaultConfig();
            LoadDefaultMessages();
            playerPrefs = dataFile.ReadObject<Dictionary<ulong, bool>>();

            cmd.AddChatCommand("masterkey", this, "ChatCommand");
            permission.RegisterPermission("masterkey.all", this); // Deprecate, use masterkey.* instead?
            permission.RegisterPermission("masterkey.boxes", this);
            permission.RegisterPermission("masterkey.cells", this);
            permission.RegisterPermission("masterkey.cupboards", this);
            permission.RegisterPermission("masterkey.doors", this);
            permission.RegisterPermission("masterkey.gates", this);
            permission.RegisterPermission("masterkey.shops", this);
            permission.RegisterPermission("masterkey.hatches", this);
        }

        #endregion

        #region Configuration

        bool logUsage;
        bool showMessages;

        protected override void LoadDefaultConfig()
        {
            Config["LogUsage"] = logUsage = GetConfig("LogUsage", true);
            Config["ShowMessages"] = showMessages = GetConfig("ShowMessages", true);
            SaveConfig();
        }

        #endregion

        #region Localization

        void LoadDefaultMessages()
        {
            lang.RegisterMessages(new Dictionary<string, string>
            {
                ["ChatCommand"] = "masterkey",
                ["Disabled"] = "MasterKey access is now disabled",
                ["Enabled"] = "MasterKey access is now enabled",
                ["MasterKeyUsed"] = "{0} ({1}) used master key at {2}",
                ["UnlockedWith"] = "Unlocked {0} with master key!"
            }, this);
        }

        #endregion

        #region Chat Command

        void ChatCommand(BasePlayer player)
        {
            if (!playerPrefs.ContainsKey(player.userID)) playerPrefs.Add(player.userID, true);
            playerPrefs[player.userID] = !playerPrefs[player.userID];
            dataFile.WriteObject(playerPrefs);

            PrintToChat(player, playerPrefs[player.userID] ? Lang("Enabled", player.UserIDString) : Lang("Disabled"));
        }

        #endregion

        #region Lock Access

        object CanUseDoor(BasePlayer player, BaseLock door)
        {
            var parent = door.parentEntity.Get(true);
            var prefab = parent.LookupPrefab();

            if (!door.IsLocked()) return true;
            if (playerPrefs.ContainsKey(player.userID) && !playerPrefs[player.userID]) return null;

            if (prefab.name.Contains("box"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.boxes")) return null;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "box"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            if (prefab.name.Contains("cell"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.cells")) return null;
                if (parent.IsOpen()) return true;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "cell"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            if (prefab.name.Contains("door"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.doors")) return null;
                if (parent.IsOpen()) return true;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "door"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            if (prefab.name.Contains("fence.gate") || prefab.name.Contains("gates.external"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.gates")) return null;
                if (parent.IsOpen()) return true;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "gate"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            if (prefab.name.Contains("shopfront"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.shops")) return null;
                if (parent.IsOpen()) return true;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "shop"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            if (prefab.name.Contains("floor"))
            {
                if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.floor")) return null;
                if (parent.IsOpen()) return true;
                if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "floor"));
                if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position));
                return true;
            }

            return null;
        }

        #endregion

        #region Cupboard Access

        void OnEntityEnter(TriggerBase trigger, BaseEntity entity)
        {
            var player = entity as BasePlayer;

            if (player == null || !(trigger is BuildPrivilegeTrigger)) return;
            if (playerPrefs.ContainsKey(player.userID) && !playerPrefs[player.userID]) return;
            if (!IsAllowed(player.UserIDString, "masterkey.all") && !IsAllowed(player.UserIDString, "masterkey.cupboards")) return;

            timer.Once(0.1f, () => player.SetPlayerFlag(BasePlayer.PlayerFlags.HasBuildingPrivilege, true));
            if (showMessages) PrintToChat(player, Lang("UnlockedWith", player.UserIDString, "cupboard"));
            if (logUsage) LogToFile(Lang("MasterKeyUsed", null, player.displayName, player.UserIDString, player.transform.position ));
        }

        #endregion

        #region Helpers

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        bool IsAllowed(string userId, string perm) => permission.UserHasPermission(userId, perm);

        string Lang(string key, string id = null, params object[] args) => string.Format(lang.GetMessage(key, this, id), args);

        void LogToFile(string text) => ConVar.Server.Log($"oxide/logs/{Title.ToLower()}_{DateTime.Now.ToString("yyyy-M-d")}.txt", text);

        #endregion
    }
}
